spring:
  application:
    name: product-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: ${queue.name}

server:
  port: 8080
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8087/eureka/
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret: ${JWT_SECRET:12345678}

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.boot: INFO
        org.hibernate.SQL: DEBUG

aws:
    s3:
      region: ${AWS_REGION}
      bucket: ${AWS_S3_BUCKET}